#!/usr/bin/env python

PKG = "turtlebot_bringup"

import sys
import unittest

import rospy
from sensor_msgs.msg import Image, LaserScan

class BugWitness(unittest.TestCase):
    def test_topic_subscribed(self):
        sub = rospy.Subscriber("scan", LaserScan, self.skip)
        pub = rospy.Publisher("camera/depth_registered/image_raw", Image, queue_size=10)
        rate = rospy.Rate(5)
        while not rospy.is_shutdown():
            if pub.get_num_connections() > 0:
                break
            rate.sleep()
        self.assertTrue(pub.get_num_connections() > 0)

    def skip(self, msg):
        pass

if __name__ == '__main__':
    import rostest
    rospy.init_node("bug_witness")
    rostest.rosrun(PKG, "bug_witness", BugWitness)
